[package]
name = "tar_gz_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
flate2 = "1.0"
tar = "0.4"
xz2 = "0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"